AllCops:
  Exclude:
    - '**/doc/*'
    - '**/pkg/*'
    - '**/spec/ruby-spec/**/*'
    - '**/vendor/**/*' # vendored dependencies
  NewCops: enable
  RubyInterpreters:
    - ruby
    - rake
  TargetRubyVersion: 2.5 # really 2.1, but 2.5 is lowest supported by rubocop

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics:
  Enabled: false
