name: gouteur

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Prepare
        run: |
          bundle install --jobs 4
          bundle exec rake compile
      - name: Test
        run: bundle exec gouteur
